_BASE_: "../Base-TESTR.yaml"
DATASETS:
  TRAIN: ("hiertext_train",)
  TEST: ("hiertext_validation",)
MODEL:
  TRANSFORMER:
    USE_POLYGON: True
    NUM_CTRL_POINTS: 16
    LOSS:
      POINT_TEXT_WEIGHT: 4.0
TEST:
  USE_LEXICON: False
  LEXICON_TYPE: 1
